version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "monkey"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o6dbh16tiby2"
s3_prefix = "monkey"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
